### ISSUE TITLE
request: Events on multiple lines

### ISSUE THREAD

**Issue by MHubschmann** [MMM-CalendarExt2/MMM-CalendarExt2#112]
Hi, super great plugin! Im using a smaller screen af my MagicMirror and im having two Monthly calendars side by side (one in lower left and one in lower right), and is therefore running out of horizontal space. All I can see is the time and then three letters of the event title like "09:00 XXX...". In this case having the event title showed on multiple lines would be great.

**Comment by klaernie** [comment]
Multiline titles are very hard to achieve - it must work for every possible calendar type, and many of the layouts do not work with multiple lines.

Feel free to propose a PR that implements this, but right now we also don't have a test suite, that could prove correctness.

On a functional side, maybe try an alternative way, like using multiple views to switch between current and next month, so both can use more space as only one is shown at a time. This is the way I personally use a next 7 days view for 3 people with private and business events trading places.

**Comment by cd36jvn** [comment]
I didn't want to create a new issue, as mine is a similar problem.  I love this module, but it would be really nice to be able to wrap text of event titles.  Unless the title is very short, there just isn't enough space to see the entire thing.

The MMM-CalendarWeek is a good example of what I'm looking for, specifically this picture:

https://github.com/heskja/MMM-CalendarWeek/raw/master/screenshots/mm.png

If there was any way to accomplish this that would be great.

**Comment by mpoxberry** [comment]
I was able to figure out some custom CSS to at least get events on the month view show up over two lines. 

```css
/* MMM-CalendarExt2 
	gets events to show on multiple lines*/
.CX2 .weekSlot .timeline {
	display: flex;
	flex-wrap: wrap;
	gap: 1px;
}
.CX2 .weekSlot .timelineSleeve {
	height: fit-content;
}
.CX2 .weekSlot .event:not(.fullday) .eventMain  {
	height: auto;
	flex-wrap: wrap;
	flex-grow: 2; /* <- change to 1 if no icon is used for calendar */
	overflow: visible;
}
```

The calendar events are created on top of the generic blank calendar (I could be wrong). These calendar events are created as rows and if you have one event in that row that requires two lines it makes the spacing for any following rows a little strange. You're experience my verify depending on other configs setup within the module.
