### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by themox** [MMM-CalendarExt2/MMM-CalendarExt2#172]
One of the recent updates appears to have introduced a memory leak.  Happy to upload any files that would help with troubleshooting.  MM keeps slowing until the computer freezes altogether.  

uname -a:
Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

node -v
16.14.0

npm -v
8.3.1

Currently running modules:
MMM-CalendarExt2 
MMM-EveryNews
MMM-GoogleTasks
MMM-Jast  
MMM-MoonPhase  
MMM-OpenWeatherMapForecast  
MMM-page-indicator  
MMM-pages  
MMM-Remote-Control (installed but not running due to issues of its own)

**Comment by KristjanESPERANTO** [comment]
This is an interesting problem. How long does it take from the start of the mirror until the freeze occurs? Is the time span usually the same? Does the freeze also occur when you disable all other modules? Which MagicMirror version do you use?

Please show the config of your MMM-CalendarExt2 module (with anonymized calendar URLs, of course).

**Comment by themox** [comment]
It usually happens over night, but I noticed the slowdown today within a few hours from reboot.  I'd say 6-8 hours from reboot/reload to frozen.  Calendar config below.  I've been using it for a while, though, and this behavior only started in the last week-ish coincident with pulling the latest from git.  I disabled the remote control module which was causing some other issues.
`
{
	module: 'MMM-CalendarExt2',
	config: {
		scanInterval: 1000*60*10,
		rotateInterval: 0,
		deduplicateEventsOn: ["title", "startDate"],
		defaultSet: {
  			view: {
				slotCount: 0,
				display: false,
			}
		},

		scenes: [
			{
				name: "DEFAULT",
				views: ["dayview","weekview"],
			}, 
			{
                                name: "Scene1",
                                views: ["dayview","weekview"],
			},
                        {
                                name: "Scene1a",
                                views: ["dayview","weekview"],
                        },
			{
				name: "Scene1b",
				views: ["monthview"],
			},
		],
		views:[
					{
						name: "shownone",
						calendars: [""],
					},
					{
						name: "dayview",
			        		mode: "daily",
						position: "top_left",
						fromNow: "0",
						slotCount: "2",
						hideOverflow: true,
						calendars: ["holidays", "mariangel", "joe", "mariangel|joe", "joe|mariangel", "soti"],
                                                transform: (event)=>{

                                                        if (event.calendarName == "joe|mariangel" || event.calendarName == "mariangel|joe") {
                                                                event.icon = "carbon:user-multiple";
                                                        }

							if (event.title.search("Margaret") > -1 || event.title.search("Gita") > -1 || event.title.search("margaret") > -1 || event.title.search("gita") > -1) {
								event.icon = "openmoji:unicorn";
							}

                                                        if (event.title.search("Becca") > -1 || event.title.search("becca") > -1) {
                                                                event.icon = "emojione:honeybee";
                                                        } else if (event.title.search("Christmas") > -1) {                     // If the event includes search term in its title,
                                                                event.icon = "noto-santa-claus-light-skin-tone";        // Set icon of that event
                                                        } else if (event.title.search("New Year") > -1){
                                                                event.icon = "fxemoji-fireworks";
                                                        } else if (event.title.search("Halloween") > -1) {
                                                                event.icon = "emojione-jack-o-lantern";
                                                        } else if (event.title.search("Easter") > -1) {
                                                                event.icon = "noto-v1:rabbit";
                                                        } else if (event.title.search("St. Patrick") > -1) {
                                                                event.icon = "noto-four-leaf-clover";
                                                        } else if (event.title.search("Birthday") > -1) {
                                                                event.icon = "noto-birthday-cake";
                                                        } else if (event.title.search("birthday") > -1) {
								event.icon = "noto-birthday-cake";
							}
                                                        return event;
                                                },
					},
					{
						name: "weekview",
						mode: "week",
						fromNow: "0", 
						slotCount: "2",
						calendars: ["holidays", "mariangel", "joe", "mariangel|joe", "joe|mariangel", "soti"],
						position: "bottom_bar",
						slotMaxHeight: "150px",
						hideOverflow: true,

						transform: (event)=>{


							if (event.calendarName == "joe|mariangel" || event.calendarName == "mariangel|joe") {
								event.icon = "carbon:user-multiple";
							}

                                                        if (event.title.search("Margaret") > -1 || event.title.search("Gita") > -1 || event.title.search("margaret") > -1 || event.title.search("gita") > -1) {
                                                                event.icon = "openmoji:unicorn";
                                                        }



							if (event.title.search("Becca") > -1 || event.title.search("becca") > -1) {
								event.icon = "emojione:honeybee";
							} else if (event.title.search("Christmas") > -1) { 			// If the event includes search term in its title,
								event.icon = "noto-santa-claus-light-skin-tone"; 	// Set icon of that event
							} else if (event.title.search("New Year") > -1){
								event.icon = "fxemoji-fireworks";
							} else if (event.title.search("Halloween") > -1) {
								event.icon = "emojione-jack-o-lantern";
							} else if (event.title.search("Easter") > -1) {
						                event.icon = "noto-v1:rabbit";
						        } else if (event.title.search("St. Patrick") > -1) {
						                event.icon = "noto-four-leaf-clover";
						        } else if (event.title.search("Birthday") > -1) {
						                event.icon = "noto-birthday-cake";
						        } else if (event.title.search("birthday") > -1) {
                                                                event.icon = "noto-birthday-cake";
                                                        }

							return event;
						},
		           		},
					{
						name: "monthview",
						mode: "week",
						title: "Long Range Calendar",
						fromNow: "0",
						slotCount: "4",
						slotMaxHeight: "180px",
						calendars: ["holidays", "mariangel", "joe", "mariangel|joe", "joe|mariangel", "soti"],
						hideOverflow:true,
						position: "middle_center",
                                                transform: (event)=>{

                                                        if (event.calendarName == "joe|mariangel" || event.calendarName == "mariangel|joe") {
                                                                event.icon = "carbon:user-multiple";
                                                        }

                                                        if (event.title.search("Margaret") > -1 || event.title.search("Gita") > -1 || event.title.search("margaret") > -1 || event.title.search("gita") > -1) {
                                                                event.icon = "openmoji:unicorn";
                                                        }

                                                        if (event.title.search("Becca") > -1 || event.title.search("becca") > -1) {
                                                                event.icon = "emojione:honeybee";
                                                        } else if (event.title.search("Christmas") > -1) {                     // If the event includes search term in its title,
                                                                event.icon = "noto-santa-claus-light-skin-tone";        // Set icon of that event
                                                        } else if (event.title.search("New Year") > -1){
                                                                event.icon = "fxemoji-fireworks";
                                                        } else if (event.title.search("Halloween") > -1) {
                                                                event.icon = "emojione-jack-o-lantern";
                                                        } else if (event.title.search("Easter") > -1) {
                                                                event.icon = "noto-v1:rabbit";
                                                        } else if (event.title.search("St. Patrick") > -1) {
                                                                event.icon = "noto-four-leaf-clover";
                                                        } else if (event.title.search("Birthday") > -1) {
                                                                event.icon = "noto-birthday-cake";
                                                        } else if (event.title.search("birthday") > -1) {
                                                                event.icon = "noto-birthday-cake";
                                                        }
                                                        return event;
                                                },
					},
				],
		calendars: [

				{
					name: "holidays",
		                	url: '*removed*',
		               		color: '#5555FF',
					className: "holidays",
					icon: "bx:bxs-calendar-star",
			        },
			        {
					name: "joe",
					url: "*removed*",
		                	color: '#DD5500',
					className: "joe",
			        	icon: "whh:zelda",
				},
			        {
					name: "mariangel",
					url: '*removed*',
		                	color: '#AADD33',
			        	className: "mariangel",
					icon: "noto-v1:rabbit-face",
			        },

                                {
                                        name: "soti",
                                        url: '*removed*',
                                        color: '#540E0E',
                                        className: "soti",
                                        icon: "fa-solid:i-cursor",
                                },

			],
		notifications: {
			"PAGE_INCREMENT" : {
				exec: "sceneNext",
			},
			"PAGE_DECREMENT" : {
				exec: "scenePrevious",
			},
			
		
			}, // end notifications
		},
	}, // end mmcalenderext2
`

**Comment by klaernie** [comment]
Re: editing: did the code block for you

My first question would be, if the problem occurs in the frontend or the backend half. I've not seen any such problem myself, so I guess isolating it to the specific module combination that causes it is also very important

**Comment by themox** [comment]
Thanks - I'm out of town for a bit so will isolate it when I return.  In the mean time, what did you do to fix the code block?  Thank you!

**Comment by TheBassfly** [comment]
This is a interesting thread, as I'm also experience random PI freezes since the last update.
I can't say exactly when it's happening, as I'm not on the Display 24/7. I just noticed from time to time every day, that my clock at MM freezed and that the whole Raspberry ist not reachable any more via VNC oder SSH. So I need to do a power cycle to get it back.

**Comment by TheBassfly** [comment]
So, after disabling the module, the Pi is now running the whole day without any issues. Unfortunately my Magic Mirror looks pretty empty now, without a working calendar. I hope the is a solution in the near future.

**Comment by TheBassfly** [comment]
Any possible solutions or do you need more input?
I would love to enable my calendar again, without restarting my pi every 8-10 hours.

**Comment by zanix** [comment]
I was having the same issue after I updated recently. My local install was around 70 commits ago before I updated.
I ended up reverting to commit 13f74d2 which was before all of the linting changes and my Pi runs without freezing or slowdown.

**Comment by zanix** [comment]
In order to revert, I reverted any changed, deleted node_module, and created a new branch based on the 13f74d2 so I would not get an update message in the updater notifications
```shell
git reset --hard
rm -rf node_modules
git checkout -b before_linting 13f74d2
npm install
```

**Comment by KristjanESPERANTO** [comment]
@zanix: Thanks for figuring that out. So https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/commit/13f74d2159d5e24b0a9a995a3651bfe474746789 is exactly the commit since the problem started to occur?

**Comment by zanix** [comment]
@KristjanESPERANTO just the last known for my particular install as I just reverted back to where I was before.
I plan on advancing the commit hash 5 at a time and see if and when the issue starts. However, it takes about 4-6 hours before it occurs so it will be slow going.

**Comment by zanix** [comment]
I'm going to start with 9945984 as that only has linter config and package.json changes and no actual code changes.

**Comment by TheBassfly** [comment]
@zanix 
Thanks for your input. I tried the same now and let's see how it is going.

**Comment by zanix** [comment]
Jumped from 9945984 to 6ca601c [[Compare 9945984..6ca601c](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/compare/9945984..6ca601c)]
No issues for 8 hours

---

Testing 926eb27 [[Compare 6ca601c..926eb27](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/compare/6ca601c..926eb27)]

**Comment by zanix** [comment]
As a note, I have been performing the following steps when I update

```shell
git reset --hard
rm -rf node_modules
git checkout -b before_linting_{SHA} {SHA}
npm install
pm2 restart mm
```

MM is running on:

```text
$ cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.1
```

I run the following modules

```text
MMM-AirNow
MMM-CalendarExt2
MMM-GoogleDocs-Notes
MMM-HomeAssistantDisplay
MMM-MyGarbage
MMM-OpenWeatherForecast
MMM-PaprikaMenu
MMM-PlexNowPlaying
MMM-Pollen
MMM-Remote-Control
MMM-SystemStats
MMM-TitanSchoolMealMenu
MMM-Traffic
MMM-Unsplash
```

**Comment by zanix** [comment]
Getting freezes, also the events are showing up on separate lines.
I'm away for a couple hours but I'll downgrade when I'm back

**Comment by zanix** [comment]
Downgrading to a4c8954

**Comment by klaernie** [comment]
Are running git bisect for figure out the problematic commit?

My entire serverside runs on kubernetes, so if my server end consumes too much memory the pod will be killed. that makes it quite hard to reproduce.

**Comment by zanix** [comment]
I have actually never heard of that command so no. I'm just manually changing the commit that is checked out.

**Comment by klaernie** [comment]
Turns out I had Prometheus running and it recorded the memory usage of that pod over the last 4 days - sadly it was constant at about 770MB.

**Comment by zanix** [comment]
> Are running git bisect for figure out the problematic commit?
This looks very handy, can't believe I never heard of it before. I should start using it.

**Comment by zanix** [comment]
As for memory or CPU usage only MM freezes up, I have not seen the Pi run out of memory nor the CPU peg at 100%.

**Comment by zanix** [comment]
a4c8954 seems stable, checking out 6af95b5
Going to leave that one for overnight as it's 9pm here

**Comment by zanix** [comment]
6af95b5 is freezing
So its either 6af95b5 or 3d6a5e2

**Comment by TheBassfly** [comment]
I'M using 13f74d2 no for a week and no issues for now.

**Comment by KristjanESPERANTO** [comment]
> [6af95b5](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/commit/6af95b5f809a31994476193171e345c464540299) is freezing So its either [6af95b5](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/commit/6af95b5f809a31994476193171e345c464540299) or [3d6a5e2](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/commit/3d6a5e2fa69c373f6ce3182b94acd47c59b07af1)

@zanix: That's odd. Can you take the current development state and roll back these changes one by one?

**Comment by zanix** [comment]
I rolled back to 3d6a5e2

**Comment by zanix** [comment]
Freezing on that one 3d6a5e2. I have already checkout out a4c8954 and it was stable so I will go back that one.

**Comment by zanix** [comment]
Yep, it's the for to forEach change in 3d6a5e2 that's causing the freezing
I think I might try the latest commit and revert just this part of the code and see what happens

**Comment by klaernie** [comment]
I'd hope that with #185 merged the problem should be gone

**Comment by zanix** [comment]
I will test this soon.
I did spot another similar condition in `CALEXT2_Event.js`
Could that also potentially have the same issue?

**Comment by klaernie** [comment]
> I did spot another similar condition in [`CALEXT2_Event.js`](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/CALEXT2_Event.js#L20)
> Could that also potentially have the same issue?

Thanks for making me look - now I grepped the rest of the codebase and found another spot where we potentially would have had the same issue. Now all three classes that have a `destroy()` method are reverted and have the linter rule disabled for that line.

**Comment by zanix** [comment]
I have updated to the latest commit, hopefully this fixed the freezing.

**Comment by zanix** [comment]
So far so good

**Comment by klaernie** [comment]
Happy to hear. I'd wait for @themox to see if the current version works better before I'd close the issue.

**Comment by TheBassfly** [comment]
I have the latest release running now for 5 days without any issues.

Thank you from my side!

**Comment by themox** [comment]
Ok, nearly 48 hrs of stability - I think we're good.  I'm going to close this.  Thanks to @klaernie for the fix and everyone else on the string for the troubleshooting.  Cheers!

**Comment by wiedsee** [comment]
https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/issues/172#issuecomment-1078609731

@zanix your custom css looks great would you like to share it wit me ?

**Comment by zanix** [comment]
> [#172 (comment)](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/issues/172#issuecomment-1078609731)
> 
> @zanix your custom css looks great would you like to share it wit me ?

Sure thing
Keep in mind my CSS affects the `week` and `daily` modes and it's not very well commented

<details><summary>Zanix's Custom CSS</summary>

```css

/* Calendar */
.CX2 .slot * {
  line-height: calc(var(--font-size) + 2px);
}
.CX2 .slot .event {
  background: inherit;
}
.CX2 .slot .slotHeader {
  background-color: inherit;
  text-transform: uppercase;
  font-size: 15px;
  font-family: "Roboto Condensed", Arial, Helvetica, sans-serif;
  font-weight: 400;
  border-bottom: 1px solid #666;
  line-height: 15px;
  padding-bottom: 5px;
  margin-bottom: 10px;
  color: #999;
}
.CX2 .slot > .slotContent {
  background: none;
}

.CX2 .daily .today .slotHeader * {
  color: #fff;
}
.CX2 .daily .fullday .eventTime {
  display: none;
}
.CX2 .period .eventIcon {
  min-width: calc(var(--font-size) * 1.5);
  min-height: calc(var(--font-size) * 1.5);
}
.CX2 .daily .period .eventTitle {
  font-size: 18px;
  line-height: normal;
}
.CX2 .daily .period .eventTime * {
  font-size: 16px;
  line-height: normal;
}

.CX2 .week .today .slotHeader * {
  color: inherit;
}
.CX2 .week .today .slotHeader {
  background-color: rgba(0, 161, 255, 0.4);
}
.CX2 .week .today .slotHeader .slotSubTitle {
  color: #fff;
}
.CX2 .week .weekSlot .eventIcon {
  display: inline-block;
}
.CX2 .week .weekSlot .eventIcon+.eventTitle {
  display: inline-block;
}

.CX2 .cellSlot.passedday .slotHeader .slotTitle,
.CX2 .cellSlot.passedday .slotHeader .slotAltTitle,
.CX2 .event.passed {
  opacity: 0.5 !important;
}
.CX2 .event.passed::before {
  background: none;
}

.CX2 .event {
  border-left-width: 3px;
  border-left-style: solid;
}
.CX2 .event.fullday {
  color: inherit;
  border-radius: 0;
}
.CX2 .week .event.fullday.overslot {
  border-top-width: 1px;
  border-top-style: solid;
}

.CX2 .slot .slotFooter {
  display: none;
}

.CX2 .weeksmark {
  display: none;
}
.CX2 .weekSlot .eventMain {
  text-overflow: unset;
}
.CX2 .weekSlot .event .eventMain {
  display: block;
  height: calc(var(--font-size) * 2.1);
}
.CX2 .weekSlot .event:not(.fullday) .endTime {
  display: inline;
}
.CX2 .weekSlot .timelineSleeve {
  height: calc((var(--font-size) * 2) + 15px);
}

/* Calendar Colors */
.CX2 .event[data-calendar-name="Maintenance"] {
  border-color: #7a570b;
}
.CX2 .event[data-calendar-name="Maintenance"] .eventIcon {
  color: #7a570b;
}
```

</details>
