### ISSUE TITLE
Daily row view disappeared from bottom_bar

### ISSUE THREAD

**Issue by cevanwells** [MMM-CalendarExt2/MMM-CalendarExt2#297]
I'm not sure what's going on here. I have a daily row view configured to be displayed on the bottom_bar area. This has worked for months, perfectly. This past week said view has disappeared from the display.

The calendars being used haven't changed to my knowledge and will display correctly if moved to a different view. I'm not very well versed in debugging MMM modules, but I have included a dump of the most recent log from startup.

Thank you for all your hard work!

```
mm  | [28.04.2023 08:52.39.603] [LOG]   Server started ...
mm  | [28.04.2023 08:52.39.604] [LOG]   Connecting socket for: updatenotification
mm  | [28.04.2023 08:52.39.605] [LOG]   Starting module helper: updatenotification
mm  | [28.04.2023 08:52.39.606] [LOG]   Connecting socket for: MMM-CalendarExt2
mm  | [28.04.2023 08:52.39.607] [LOG]   Connecting socket for: MMM-Trello
mm  | [28.04.2023 08:52.39.607] [LOG]   Starting node helper for: MMM-Trello
mm  | [28.04.2023 08:52.39.608] [LOG]   Sockets connected & modules started ...
mm  | [28.04.2023 08:52.39.835] [LOG]   Launching application.
mm  | MESA-LOADER: failed to retrieve device information
mm  | MESA-LOADER: failed to retrieve device information
mm  | MESA-LOADER: failed to retrieve device information
mm  | [28.04.2023 08:52.42.945] [INFO]  Checking git for module: MMM-CalendarExt2
mm  | [28.04.2023 08:52.42.983] [LOG]   [CALEXT2] calendar:family >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.007] [LOG]   [CALEXT2] calendar:school >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.010] [LOG]   [CALEXT2] calendar:asf_oncall >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.017] [LOG]   [CALEXT2] calendar:asf >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.022] [LOG]   [CALEXT2] calendar:church >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.026] [LOG]   [CALEXT2] calendar:meals >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.030] [LOG]   [CALEXT2] calendar:holidays >> Scanning start with interval:1800000
mm  | [28.04.2023 08:52.43.074] [INFO]  Checking git for module: MMM-WeeklySchedule
mm  | [28.04.2023 08:52.43.212] [INFO]  Checking git for module: MMM-Trello
mm  | [28.04.2023 08:52.43.263] [INFO]  Checking git for module: MagicMirror
mm  | [28.04.2023 08:52.44.093] [LOG]   [CALEXT2] calendar:meals >> Scanned: 0, Selected: 0
mm  | [28.04.2023 08:52.44.448] [LOG]   [CALEXT2] calendar:church >> Scanned: 163, Selected: 163
mm  | [28.04.2023 08:52.44.636] [LOG]   [CALEXT2] calendar:asf >> Scanned: 75, Selected: 75
mm  | [28.04.2023 08:52.44.674] [LOG]   [CALEXT2] calendar:school >> Scanned: 18, Selected: 18
mm  | [28.04.2023 08:52.44.852] [LOG]   [CALEXT2] calendar:asf_oncall >> Scanned: 7, Selected: 7
mm  | [28.04.2023 08:52.44.867] [LOG]   [CALEXT2] calendar:holidays >> Scanned: 0, Selected: 0
mm  | [28.04.2023 08:52.45.601] [LOG]   [CALEXT2] calendar:family >> Scanned: 140, Selected: 140
mm  | [28.04.2023 08:52.49.828] [ERROR] Failed to retrieve repo info for MagicMirror: TypeError: Cannot read properties of null (reading '1')
```

**Comment by klaernie** [comment]
Could you please post your config, both the JS and CSS? Don't forget to censor your calendar URLs if you don't want to make them public knowledge;)

**Comment by cevanwells** [comment]
Sounds good to me. I've removed calendar URLs and API keys.

config.js
```javascript
/* MagicMirror² Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "0.0.0.0", 	// Address to listen on, can be:
	// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	// - another specific IPv4/6 to listen on a specific interface
	// - "0.0.0.0", "::" to listen on any interface
	// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
					  // you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.7.0/24"], 	// Set [] to allow all IP addresses
															  // or add a specific IPv4 of 192.168.1.5 :
															  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															  // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR", "DEBUG"], // Add "DEBUG" for even more logging
	timeFormat: 12,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				displaySeconds: false,
			}
		},
		{
			module: "MMM-CalendarExt2",
			config: {
				rotateInterval: 10*60*1000,
				animationSpeed: 0,
				calendars: [
					{
						name: "family",
						icon: "bi:house-heart-fill",
						url: "",
					},
					{
						name: "school",
						icon: "ic:round-school",
						url: "",
					},
					{
						name: "asf_oncall",
						icon: "fa-solid:feather",
						url: "",
						replaceTitle: [
							["On Call - tagteam", "On Call"],
						],
					},
					{
						name: "asf",
						icon: "fa-solid:feather",
						url: "",
					},
					{
						name: "church",
						icon: "fluent-emoji-high-contrast:church",
						url: "",
					},
					//{
						//name: "cross_country",
						//icon: "ic:round-directions-run",
						//url: "",
					//},
					{
						name: "meals",
						icon: "fa-solid:utensils",
						url: "",
					},
					{
					    name: "holidays",
					    icon: "noto-beach-with-umbrella",
					    url: "",
					},
				],
				views: [
					{
						name: "view_meals",
						title: "Meals",
						position: "top_left",
						calendars: ["family"],
						mode: "upcoming",
						maxDays: 7,
						useEventTimeRelative: false,
						hideFooter: true,
						className: "meals",
						hideOverflow: false,
					},
					{
						name: "view_week",
						position: "bottom_bar",
						className: "week",
						calendars: ["family", "asf", "asf_oncall", "school", "church", "holidays"],
						mode: "daily",
						type: "row",
						slotCount: 7,
						fromNow: 0,
						slotTitleFormat: "ddd",
						slotSubTitleFormat: "MMM Do",
						hideOverflow: true,
                		filterPassedEvent: false,
                		transform: (event) => {
  							if (event.title == "Kung Fu" | event.title == "Kung fu" | event.title == "kung fu") {
    								event.icon = "ic:round-sports-martial-arts";
  							}
  							if (event.title.search("birthday") > -1) {
  								event.icon = "fa:birthday-cake";
  							}
  							return event; // Return that event.
						},
					},
				],
				scenes: [
					{
						name: "DEFAULT",
						views: [],
					},
				],
			},
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				locationID: "",
				apiKey: ""
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "daily",
				locationID: "",
				apiKey: "",
				appendLocationNameToHeader: false,
				fade: false,
				maxNumberOfDays: 2,
				initialLoadDelay: 1000,
				maxEntries: 1
			}
		},
		{
			module: "MMM-WeeklySchedule",
			position: "top_left",
			header: "Reminders",
			config: {
				schedule: {
					timeslots: ["", "", "", "", "", "", "", "", "", ""],
					lessons: {
						mon: ["Lunch packed", "Computer", "Homework", "Shoes", "Glasses", "Breakfast", "XC clothes"],
						tue: ["Lunch packed", "Computer", "Homework", "Shoes", "Glasses", "Breakfast", "XC clothes", "Kung Fu clothes"],
						wed: ["Lunch packed", "Computer", "Homework", "Shoes", "Glasses", "Breakfast", "XC clothes"],
						thu: ["Lunch packed", "Computer", "Homework", "Shoes", "Glasses", "Breakfast", "XC clothes", "Kung Fu clothes"],
						fri: ["Lunch packed", "Computer", "Homework", "Shoes", "Glasses", "Breakfast", "XC clothes"],
						sat: ["Breakfast", "Runlists", "Kung Fu Clothes"],
						sun: ["Breakfast (fasting?)", "Scriptures", "Glasses", "Shoes"],
					}
				},
				showNextDayAfter: undefined,
			}
		},
		{
			module: "MMM-Trello",
			position: "top_right",
			header: "Prayer Roll",
			config: {
				api_key: "",
				token: "",
				showTitle: true,
				titleClass: "small",
				wholeList: true,
				showDescription: false,
				animationSpeed: 0,
				list: "",
			},
		},
		{
			module: "MMM-Trello",
			position: "top_center",
			header: "Coming Storms",
			config: {
				api_key: "",
				token: "",
				showTitle: true,
				wholeList: true,
				animationSpeed: 0,
				showChecklists: false,
				list: "",
			},
		},
		{
			module: "MMM-Trello",
			position: "top_right",
			header: "Bright Futures",
			config: {
				api_key: "",
				token: "",
				showTitle: true,
				titleClass: "small",
				wholeList: true,
				animationSpeed: 0,
				showChecklists: false,
				list: "",
			},
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
	module.exports = config;
}

``` 

custom.css
```css
body {
  margin:20px;
  height: calc(100% - 20px);
  width: calc(100% - 30px);
  background: inherit;
}

/* meals view -- remove slot header*/
.CX2 .meals .slotHeader {
    display: none;
}

/* meals view -- float time to right */
.CX2 .meals .period .eventTitle {
    float: left;
}



/* remove time information from event title */
.CX2 .daily .eventTime {
    display:none;
}

/* remove background from events */
.CX2 .slot .event{
    background: none;
}
.CX2 .slot > .slotContent {
    background: none;
}
.CX2 .event.passed::before {
    background:  none;
}
.CX2 .event.fullday {
    color: #fff;
}

/* increase font size of events */
.CX2 .period .eventTitle {
    font-size: 20px;
    font-weight: 200;
    line-height: 22px;
}


/* shrink event icon */
.CX2 .period .eventIcon {
    min-width: calc(var(--font-size));
    min-height: calc(var(--font-size));
    margin-right: 6px;
    float: left;
}


/* remove background from day titles */
.CX2 .slot .slotHeader {
    background-color: inherit;
    text-transform: uppercase;
    font-size: 22px;
    /* font-family: "Roboto Condensed", Arial, Helvetica, sans-serif; */
    font-weight: 400;
    border-bottom: 1px solid #666;
    line-height: 15px;
    padding-bottom: 5px;
    margin-bottom: 10px;
    color: #999;
}
.CX2 .today .slotHeader * {
    color: inherit;
}
```
