### ISSUE TITLE
Background color?

### ISSUE THREAD

**Issue by ingo916** [MMM-CalendarExt2/MMM-CalendarExt2#73]
Does anyone know where in the css file I can change to color of the calendar slots when they are empty? It appears to be a light shade of black and I want to make it all black. 
![4B157722-E5DB-45E6-9336-5C6BAD01D885](https://user-images.githubusercontent.com/41309095/80923525-34fefd80-8d39-11ea-99f2-106f637d5a7d.jpeg)

**Comment by klaernie** [comment]
Put this into `custom.css`:
```css
.CX2 .slot > .slotContent {
    background: none;
}
```
